---
title: "week-8-hw"
author: "Laura Trejo"
date: "March 1, 2017"
output: html_document
---

```{r}

#Example Data: Housing Prices 
housing <- read.csv("~/Desktop/eeb-177/lab_hw/Rgraphics/dataSets/landdata-states.csv")
head(housing[1:5])

#base histogram 
hist(housing$Home.Value)

#gg histogram 
library(ggplot2)
ggplot(housing, aes(x = Home.Value)) + geom_histogram()

#base scatterplot with color 
plot(Home.Value ~ Date, data=subset(housing, State == "MA"))
points(Home.Value ~ Date, col="red",data=subset(housing, State == "TX"))
legend(1975, 400000, c("MA", "TX"), title="State",col=c("black","red"),pch=c(1, 1))

#gg scatter w/color
ggplot(subset(housing, State %in% c("MA", "TX")),aes(x=Date,y=Home.Value,color=State))+geom_point()

#gg scatter with geo 
hp2001Q1 <- subset(housing, Date == 2001.25) 
ggplot(hp2001Q1,aes(y = Structure.Cost, x = Land.Value)) +geom_point()

#log 
ggplot(hp2001Q1,aes(y = Structure.Cost, x = log(Land.Value))) +geom_point()

#regression line 
hp2001Q1$pred.SC <- predict(lm(Structure.Cost ~ log(Land.Value), data = hp2001Q1))
p1 <- ggplot(hp2001Q1, aes(x = log(Land.Value), y = Structure.Cost))
p1 + geom_point(aes(color = Home.Value)) + geom_line(aes(y = pred.SC))

#smoother 
p1 + geom_point(aes(color = Home.Value)) +geom_smooth()

#label points 
p1 + geom_text(aes(label=State), size = 3)

#greppel 
install.packages("ggrepel") 
library("ggrepel")
p1 + geom_point() + geom_text_repel(aes(label=State), size = 3)

#variables mapped to aes
p1 + geom_point (aes(size = 2), color="red") # this is fine -- all points red

#Mapping Variables to other Aesthetics
p1 + geom_point(aes(color=Home.Value, shape = region))

#Statistical Transformations
  #default statistic 
args(geom_histogram)
args(stat_bin)

#default histogram for Home.Value
p2 <- ggplot(housing, aes(x = Home.Value))
p2 + geom_histogram()

#change binwidth
p2 + geom_histogram (stat = "bin", binwidth=4000)

housing.sum <- aggregate(housing["Home.Value"], housing["State"], FUN=mean)
rbind(head(housing.sum), tail(housing.sum))
#ggplot(housing.sum, aes(x=State, y=Home.Value)) + geom_bar()

ggplot(housing.sum, aes(x=State, y=Home.Value)) + geom_bar(stat="identity")

#Scale Modification 
p3 <- ggplot(housing,aes(x = State,y = Home.Price.Index)) + theme(legend.position="top",
axis.text=element_text(size = 6))
(p4 <- p3 + geom_point(aes(color = Date),alpha = 0.5,size = 1.5,position = position_jitter(width = 0.25, height = 0)))

#modify the breaks for xaxis and color scales 
p4 + scale_x_discrete(name="State Abbreviation") + scale_color_continuous(name="",breaks = c(1976, 1994, 2013),labels = c("'76", "'94", "'13"))

#change low and high values to blue and red 
p4 + scale_x_discrete(name="State Abbreviation") + scale_color_continuous(name="", breaks = c(1976, 1994, 201), labels = c("'76", "'94", "'13"), low = "blue", high = "red")

 low = "blue"
 high = "red"
#using different color scales
p4 + scale_color_gradient2(name="",breaks = c(1976, 1994, 2013),labels = c("'76", "'94", "'13"),low = "blue", high = "red", mid = "gray60",midpoint = 1994)



#Trend in Housing Prices 
p5 <- ggplot(housing, aes(x = Date, y = Home.Value))
p5 + geom_line(aes(color = State))

#Faceting 
(p5 <- p5 + geom_line() + facet_wrap(~State, ncol = 10))

#Themes
p5 + theme_linedraw()

#Date 
p5 + theme_light()

#Overriding Theme defaults 
p5 + theme_minimal() + theme(text = element_text(color = "turquoise"))

#Creating and Saving new themes

theme_new <- theme_bw() + theme(plot.background = element_rect(size = 1, color = "blue", fill = "black"), text=element_text(size = 12, family = "Serif", color = "ivory"), axis.text.y = element_text(colour = "purple"), axis.text.x = element_text(colour = "red"), panel.background = element_rect(fill = "pink"), strip.background = element_rect(fill = ("orange")))


p5 + theme_new

#FAQ
housing.byyear <- aggregate(cbind(Home.Value, Land.Value) ~ Date, data = housing, mean)
ggplot(housing.byyear, aes(x=Date)) + geom_line(aes(y=Home.Value), color="red") + geom_line(aes(y=Land.Value), color="blue")

library(tidyr) 
home.land.byyear <- gather(housing.byyear, value = "value", key = "type", Home.Value, Land.Value)
ggplot(home.land.byyear, aes(x=Date, y=value, color=type)) + geom_line()

```

```{r}
#Exercise I 
dat <- read.csv("/home/eeb177-student/Desktop/eeb-177/lab_hw/Rgraphics/dataSets/EconomistData.csv")
head(dat)
ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point(aes(size = 2), color = "blue") + geom_point(aes(color = Region, size = HDI.Rank))

```

```{r}
#Exercise II
dat <- read.csv("/home/eeb177-student/Desktop/eeb-177/lab_hw/Rgraphics/dataSets/EconomistData.csv")
head(dat)
ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point() + geom_smooth()
?stat_smooth
ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point() + geom_smooth(method = "lm")
?loess
ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point() + geom_smooth(geom = "line")
ggplot(dat, aes(x = CPI, y = HDI, size = HDI.Rank)) + geom_point() + geom_smooth(span = .2)


```

```{r}
#Exercise III

dat <- read.csv("/home/eeb177-student/Desktop/eeb-177/lab_hw/Rgraphics/dataSets/EconomistData.csv")
head(dat)
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point(aes(color = Region)) +  scale_x_discrete(name="Corruption Perception Index ") + scale_y_continuous(name="Human Development Index") + scale_color_manual(name = "Region of the world",
values = c("Blue","Red","Green","Yellow","Purple","Pink"))



```

```{r}
#Challenge: Recreate the economist graph 
## install.packages("ggrepel") 
library("ggrepel")
dat <- read.csv("/home/eeb177-student/Desktop/eeb-177/lab_hw/Rgraphics/dataSets/EconomistData.csv")
head(dat)
points_label <- c( "Brazil", "Russia", "China", "South Africa", "Spain", " France", "Germany", "Japan") 
countries_label <- c("Venezuela", "Iraq", "Myanmar", "Sudan","Afghanistan", "Congo", "Greece", "Argentina", "India", "Italy",  "Botswana", "Cape Verde", "Bhutan", "Rwanda", "United States", "Britain", "Barbados", "Norway", "New Zealand", "Singapore")
ggplot(dat, aes(x = CPI, y = HDI)) + geom_point(aes(color = Region), shape = 1, size = 4) + geom_text (aes(label=Country), size = 2, data = subset(dat, Country %in% countries_label)) + scale_x_discrete(name="Corruption Perception Index, 2011 (10=least corrupt ") + scale_y_continuous(name="Human Development Index") + geom_smooth(aes(group = 1), method = "lm", formula = y ~ log(x), se = FALSE, color = "red") + geom_text_repel (aes(label = Country), size = 2, data = subset(dat, Country %in% points_label), force = 10) + ggtitle("Corruption and Human development")



```

